{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: {{ include "istio-operator.name" . }}
    helm.sh/chart: {{ include "istio-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: webhook
  {{- if semverCompare ">= 1.7.0" .Values.istioVersion }}
  name: "{{ include "istio-operator.fullname" . }}{{ .Values.operatorComponentSuffix }}-webhook"
  {{- else }}
  name: "istio-operator-webhook"
  {{- end }}
webhooks:
- clientConfig:
    service:
      {{- if semverCompare ">= 1.7.0" .Values.istioVersion }}
      name: "{{ include "istio-operator.fullname" . }}{{ .Values.operatorComponentSuffix }}"
      {{- else }}
      name: "istio-operator-webhook"
      {{- end }}
      namespace: {{ .Release.Namespace }}
      path: /validate-istio-config
  failurePolicy: Ignore
  matchPolicy: Exact
  name: istio.validation.banzaicloud.io
  rules:
  - apiGroups:
    - istio.banzaicloud.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - istios
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
  admissionReviewVersions: ["v1beta1", "v1"]
{{- end -}}
