apiVersion: v1
name: istio-operator
description: istio-operator manages Istio deployments on Kubernetes
keywords:
  - istio
  - operator
sources:
  - https://github.com/banzaicloud/istio-operator/tree/v2
icon: https://istio.io/latest/img/istio-whitelogo-bluebackground-framed.svg

# Based on support status of Istio releases: https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases
kubeVersion: ">= 1.20.0-0 <= 1.23.0-0"

version: 2.0.9
appVersion: "v2.13.0-rc.0"
