# Default values for istio-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  image:
    repository: ghcr.io/banzaicloud/istio-operator
    tag: 0.8.8
    pullPolicy: IfNotPresent
  extraArgs: []
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

istioVersion: "1.8"

# If you want the operator to expose the /metrics
prometheusMetrics:
  enabled: true
  # Enable or disable the auth proxy (https://github.com/brancz/kube-rbac-proxy)
  # which protects your /metrics endpoint.
  authProxy:
    enabled: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0
      pullPolicy: IfNotPresent

## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  enabled: true
  ## Pod Security Policies
  ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  ##
  psp:
    enabled: false

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []

operatorComponentSuffix: ""

leaderElection:
  enabled: true
  namespace: "istio-system"
  nameOverride: ""

webhook:
  enabled: true
