apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: istios.istio.banzaicloud.io
spec:
  group: istio.banzaicloud.io
  names:
    kind: Istio
    plural: istios
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoInjectionNamespaces:
              description: List of namespaces to label with sidecar auto injection
                enabled
              items:
                type: string
              type: array
            citadel:
              description: Citadel configuration options
              properties:
                replicaCount:
                  format: int32
                  type: integer
              type: object
            controlPlaneSecurityEnabled:
              description: ControlPlaneSecurityEnabled control plane services are
                communicating through mTLS
              type: boolean
            excludeIPRanges:
              type: string
            galley:
              description: Galley configuration options
              properties:
                replicaCount:
                  format: int32
                  type: integer
              type: object
            gateways:
              description: Gateways configuration options
              properties:
                maxReplicas:
                  format: int32
                  type: integer
                minReplicas:
                  format: int32
                  type: integer
                replicaCount:
                  format: int32
                  type: integer
              type: object
            includeIPRanges:
              type: string
            mixer:
              description: Mixer configuration options
              properties:
                maxReplicas:
                  format: int32
                  type: integer
                minReplicas:
                  format: int32
                  type: integer
                replicaCount:
                  format: int32
                  type: integer
              type: object
            mtls:
              type: boolean
            pilot:
              description: Pilot configuration options
              properties:
                maxReplicas:
                  format: int32
                  type: integer
                minReplicas:
                  format: int32
                  type: integer
                replicaCount:
                  format: int32
                  type: integer
              type: object
            sidecarInjector:
              description: SidecarInjector configuration options
              properties:
                replicaCount:
                  format: int32
                  type: integer
              type: object
          required:
          - mtls
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
