apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample
spec:
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  sds:
    enabled: false
  pilot:
    image: "gcr.io/istio-release/pilot:release-1.1-latest-daily"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
  citadel:
    image: "gcr.io/istio-release/citadel:release-1.1-latest-daily"
    replicaCount: 1
  galley:
    image: "gcr.io/istio-release/galley:release-1.1-latest-daily"
    replicaCount: 1
  gateways:
    ingress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
    egress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
    k8singress:
      enabled: false
  mixer:
    image: "gcr.io/istio-release/mixer:release-1.1-latest-daily"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    image: "gcr.io/istio-release/sidecar_injector:release-1.1-latest-daily"
    replicaCount: 1
    rewriteAppHTTPProbe: true
  nodeAgent:
    enabled: false
    image: "gcr.io/istio-release/node-agent-k8s:release-1.1-latest-daily"
  proxy:
    image: "gcr.io/istio-release/proxyv2:release-1.1-latest-daily"
    enableCoreDump: false
  proxyInit:
    image: "gcr.io/istio-release/proxy_init:release-1.1-latest-daily"
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
