apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample-v110x
spec:
  version: "1.10.3"
  pilot:
    spiffe:
      operatorEndpoints:
        enabled: true
