apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample
spec:
<<<<<<< HEAD
  version: "1.6.8"
=======
  version: "1.7.0-beta.1"
>>>>>>> Bump default Istio version to 1.7.0-beta.1
  meshPolicy:
    mtlsMode: PERMISSIVE
  autoMtls: true
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  mountMtlsCerts: false
  # priorityClassName: system-cluster-critical
  defaultResources:
    requests:
      cpu: 10m
  mixerlessTelemetry:
    enabled: true
  istiod:
    enabled: true
    enableAnalysis: true
    enableStatus: true
  pilot:
    enabled: true
    image: "docker.io/istio/pilot:1.6.8"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
    certProvider: "istiod"
  gateways:
    enabled: true
    ingress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "LoadBalancer"
      loadBalancerIP: ""
      serviceAnnotations: {}
      serviceLabels: {}
      runAsRoot: true
      ports:
        - port: 15021
          targetPort: 15021
          name: status-port
        - port: 80
          targetPort: 8080
          name: http2
        - port: 443
          targetPort: 8443
          name: https
        - port: 15443
          targetPort: 15443
          name: tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
    egress:
      enabled: false
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "ClusterIP"
      serviceAnnotations: {}
      serviceLabels: {}
      runAsRoot: true
      ports:
        - port: 80
          targetPort: 8080
          name: http2
        - port: 443
          targetPort: 8443
          name: https
        - port: 15443
          targetPort: 15443
          name: tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 256Mi
    k8singress:
      enabled: false
  policy:
    enabled: false
<<<<<<< HEAD
    image: "docker.io/istio/mixer:1.6.8"
=======
    image: "docker.io/istio/mixer:1.7.0-beta.1"
>>>>>>> Bump default Istio version to 1.7.0-beta.1
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  telemetry:
    enabled: false
<<<<<<< HEAD
    image: "docker.io/istio/mixer:1.6.8"
=======
    image: "docker.io/istio/mixer:1.7.0-beta.1"
>>>>>>> Bump default Istio version to 1.7.0-beta.1
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  proxy:
<<<<<<< HEAD
    image: "docker.io/istio/proxyv2:1.6.8"
=======
    image: "docker.io/istio/proxyv2:1.7.0-beta.1"
>>>>>>> Bump default Istio version to 1.7.0-beta.1
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: "TEXT"
    enableCoreDump: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
  proxyInit:
<<<<<<< HEAD
    image: "docker.io/istio/proxyv2:1.6.8"
=======
    image: "docker.io/istio/proxyv2:1.7.0-beta.1"
>>>>>>> Bump default Istio version to 1.7.0-beta.1
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  tracing:
    enabled: true
    tracer: zipkin
    zipkin:
      address: zipkin.istio-system:9411
    datadog:
        address: $(HOST_IP):8126
    lightstep:
        address: lightstep-satellite.lightstep:9292
        accessToken: <access-token>
  localityLB:
    enabled: false
    # distribute:
    # - from: "us-central1/*"
    #   to:
    #     "us-central1/*": 80
    #     "us-central2/*": 20
    # failover:
    # - from: us-east
    #   to: eu-west
    # - from: us-west
    #   to: us-east
  jwtPolicy: "first-party-jwt"
