apiVersion: istio.banzaicloud.io/v1beta1
kind: RemoteIstio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: remoteistio-sample
spec:
  autoInjectionNamespaces:
  - "default"
  includeIPRanges: "*"
  excludeIPRanges: ""
  enabledServices:
  - name: "istio-pilot"
    labelSelector: "istio=pilot"
  - name: "istio-policy"
    labelSelector: "istio-mixer-type=policy"
  - name: "istio-statsd"
    labelSelector: "statsd-prom-bridge"
  - name: "istio-telemetry"
    labelSelector: "istio-mixer-type=telemetry"
  - name: "zipkin"
    labelSelector: "app=jaeger"
  controlPlaneSecurityEnabled: true
  citadel:
      image: "istio/citadel:1.0.9"
      replicaCount: 1
  sidecarInjector:
      image: "istio/sidecar_injector:1.0.9"
      replicaCount: 1
  proxy:
      image: "istio/proxyv2:1.0.9"
