apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample
spec:
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  pilot:
    image: "istio/pilot:1.0.8"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
  citadel:
    image: "istio/citadel:1.0.8"
    replicaCount: 1
  galley:
    image: "istio/galley:1.0.8"
    replicaCount: 1
  gateways:
    ingress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
    egress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
  mixer:
    image: "istio/mixer:1.0.8"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    image: "istio/sidecar_injector:1.0.8"
    replicaCount: 1
  proxy:
    image: "istio/proxyv2:1.0.8"
  tracing:
    zipkin:
      address: zipkin.jaeger-system:9411
