apiVersion: v1
kind: Service
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    istio.io/rev: {{ include "namespaced-revision" . }}
    install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.istio.io/component: "Pilot"
    app: istiod
    istio: pilot
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 15010
      name: grpc-xds # plaintext
      protocol: TCP
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
      protocol: TCP
    - port: 443
      name: https-webhook # validation and injection
      targetPort: 15017
      protocol: TCP
    - port: 15014
      name: http-monitoring # prometheus stats
      protocol: TCP
  selector:
    app: istiod
    istio.io/rev: {{ include "namespaced-revision" . }}
---
